---
deployment:
  tasks:
    - NODE_OPTIONS="--max-old-space-size=8192" /usr/bin/npm --prefix /home/xcore/repositories2/nordfi-score-finland install
    - NODE_OPTIONS="--max-old-space-size=8192" /usr/bin/npm --prefix /home/xcore/repositories2/nordfi-score-finland run build
    - /bin/rm -rf /home/xcore/public_html/*
    - /bin/cp -r /home/xcore/repositories2/nordfi-score-finland/dist/* /home/xcore/public_html/
